apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wsu5lclxt-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:4d22c6b8125d8bacfb676c2b3c90bdcc06313130@sha256:15356ec75110830fe6cd85d31964de8b9e7286c887ae9396604a9233cff29b62
          name: container-image
